package:
  name: delimited_protobuf
  version: 0.0.2

source:
  git_url: https://github.com/soulmachine/delimited-protobuf

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - protobuf

about:
  home: https://github.com/soulmachine/delimited-protobuf
  license: Apache License 2.0
  license_file: LICENSE
  summary: Save multiple Protobuf messages to a file
